framework:
    default_locale: 'fr'      # langue par défaut du site
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - 'en'           # si une traduction n'existe pas en français, Symfony utilisera l'anglais