parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Twig\CartExtension:
        tags:
            - { name: twig.extension }

    # Force le listener Doctrine à être enregistré
    App\EventListener\ContactSentAtListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }